# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
    push:
        branches: ["main"]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    build:
        runs-on: self-hosted

        steps:
            - uses: actions/checkout@v4
            - name: Check Python version
              run: python3 --version
            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Stop old app
              run: pkill -f "app.py" || true
            - name: 🚀 Run Flask app
              run: |
                  nohup python3 app.py > app.log 2>&1 &
                  echo $! > app.pid

            - name: Verify Flask app
              run: |
                if ps -p $(cat app.pid) > /dev/null; then
                  echo "App started successfully"
                else
                  echo "App failed" && exit 1
                fi


            - name: moving on
              run: echo "next step"
